gText_Birch_Welcome::
	.string "Welcome to KINGTONY's edited rom!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Let's not waste any more time here\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Tell me about yourself$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
